"""Create fake data

Revision ID: 2e19bc295fb6
Revises: 0ad64747ac82
Create Date: 2024-02-19 17:38:16.865723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e19bc295fb6'
down_revision = '0ad64747ac82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
